<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    /**
     * Seed the surahs table with all 114 surahs
     */
    public function run(): void
    {
        $surahs = [
            ['surah_number' => 1, 'name_arabic' => 'الفاتحة', 'name_english' => 'Al-Fatiha', 'name_transliteration' => 'Al-Fātiḥah', 'revelation_type' => 'Meccan', 'total_verses' => 7],
            ['surah_number' => 2, 'name_arabic' => 'البقرة', 'name_english' => 'Al-Baqarah', 'name_transliteration' => 'Al-Baqarah', 'revelation_type' => 'Medinan', 'total_verses' => 286],
            ['surah_number' => 3, 'name_arabic' => 'آل عمران', 'name_english' => 'Ali \'Imran', 'name_transliteration' => 'Āli ʿImrān', 'revelation_type' => 'Medinan', 'total_verses' => 200],
            ['surah_number' => 4, 'name_arabic' => 'النساء', 'name_english' => 'An-Nisa', 'name_transliteration' => 'An-Nisāʾ', 'revelation_type' => 'Medinan', 'total_verses' => 176],
            ['surah_number' => 5, 'name_arabic' => 'المائدة', 'name_english' => 'Al-Maidah', 'name_transliteration' => 'Al-Māʾidah', 'revelation_type' => 'Medinan', 'total_verses' => 120],
            ['surah_number' => 6, 'name_arabic' => 'الأنعام', 'name_english' => 'Al-An\'am', 'name_transliteration' => 'Al-Anʿām', 'revelation_type' => 'Meccan', 'total_verses' => 165],
            ['surah_number' => 7, 'name_arabic' => 'الأعراف', 'name_english' => 'Al-A\'raf', 'name_transliteration' => 'Al-Aʿrāf', 'revelation_type' => 'Meccan', 'total_verses' => 206],
            ['surah_number' => 8, 'name_arabic' => 'الأنفال', 'name_english' => 'Al-Anfal', 'name_transliteration' => 'Al-Anfāl', 'revelation_type' => 'Medinan', 'total_verses' => 75],
            ['surah_number' => 9, 'name_arabic' => 'التوبة', 'name_english' => 'At-Tawbah', 'name_transliteration' => 'At-Tawbah', 'revelation_type' => 'Medinan', 'total_verses' => 129],
            ['surah_number' => 10, 'name_arabic' => 'يونس', 'name_english' => 'Yunus', 'name_transliteration' => 'Yūnus', 'revelation_type' => 'Meccan', 'total_verses' => 109],
            ['surah_number' => 11, 'name_arabic' => 'هود', 'name_english' => 'Hud', 'name_transliteration' => 'Hūd', 'revelation_type' => 'Meccan', 'total_verses' => 123],
            ['surah_number' => 12, 'name_arabic' => 'يوسف', 'name_english' => 'Yusuf', 'name_transliteration' => 'Yūsuf', 'revelation_type' => 'Meccan', 'total_verses' => 111],
            ['surah_number' => 13, 'name_arabic' => 'الرعد', 'name_english' => 'Ar-Ra\'d', 'name_transliteration' => 'Ar-Raʿd', 'revelation_type' => 'Medinan', 'total_verses' => 43],
            ['surah_number' => 14, 'name_arabic' => 'ابراهيم', 'name_english' => 'Ibrahim', 'name_transliteration' => 'Ibrāhīm', 'revelation_type' => 'Meccan', 'total_verses' => 52],
            ['surah_number' => 15, 'name_arabic' => 'الحجر', 'name_english' => 'Al-Hijr', 'name_transliteration' => 'Al-Ḥijr', 'revelation_type' => 'Meccan', 'total_verses' => 99],
            ['surah_number' => 16, 'name_arabic' => 'النحل', 'name_english' => 'An-Nahl', 'name_transliteration' => 'An-Naḥl', 'revelation_type' => 'Meccan', 'total_verses' => 128],
            ['surah_number' => 17, 'name_arabic' => 'الإسراء', 'name_english' => 'Al-Isra', 'name_transliteration' => 'Al-Isrāʾ', 'revelation_type' => 'Meccan', 'total_verses' => 111],
            ['surah_number' => 18, 'name_arabic' => 'الكهف', 'name_english' => 'Al-Kahf', 'name_transliteration' => 'Al-Kahf', 'revelation_type' => 'Meccan', 'total_verses' => 110],
            ['surah_number' => 19, 'name_arabic' => 'مريم', 'name_english' => 'Maryam', 'name_transliteration' => 'Maryam', 'revelation_type' => 'Meccan', 'total_verses' => 98],
            ['surah_number' => 20, 'name_arabic' => 'طه', 'name_english' => 'Taha', 'name_transliteration' => 'Ṭāhā', 'revelation_type' => 'Meccan', 'total_verses' => 135],
            ['surah_number' => 21, 'name_arabic' => 'الأنبياء', 'name_english' => 'Al-Anbya', 'name_transliteration' => 'Al-Anbiyāʾ', 'revelation_type' => 'Meccan', 'total_verses' => 112],
            ['surah_number' => 22, 'name_arabic' => 'الحج', 'name_english' => 'Al-Hajj', 'name_transliteration' => 'Al-Ḥajj', 'revelation_type' => 'Medinan', 'total_verses' => 78],
            ['surah_number' => 23, 'name_arabic' => 'المؤمنون', 'name_english' => 'Al-Mu\'minun', 'name_transliteration' => 'Al-Muʾminūn', 'revelation_type' => 'Meccan', 'total_verses' => 118],
            ['surah_number' => 24, 'name_arabic' => 'النور', 'name_english' => 'An-Nur', 'name_transliteration' => 'An-Nūr', 'revelation_type' => 'Medinan', 'total_verses' => 64],
            ['surah_number' => 25, 'name_arabic' => 'الفرقان', 'name_english' => 'Al-Furqan', 'name_transliteration' => 'Al-Furqān', 'revelation_type' => 'Meccan', 'total_verses' => 77],
            ['surah_number' => 26, 'name_arabic' => 'الشعراء', 'name_english' => 'Ash-Shu\'ara', 'name_transliteration' => 'Ash-Shuʿarāʾ', 'revelation_type' => 'Meccan', 'total_verses' => 227],
            ['surah_number' => 27, 'name_arabic' => 'النمل', 'name_english' => 'An-Naml', 'name_transliteration' => 'An-Naml', 'revelation_type' => 'Meccan', 'total_verses' => 93],
            ['surah_number' => 28, 'name_arabic' => 'القصص', 'name_english' => 'Al-Qasas', 'name_transliteration' => 'Al-Qaṣaṣ', 'revelation_type' => 'Meccan', 'total_verses' => 88],
            ['surah_number' => 29, 'name_arabic' => 'العنكبوت', 'name_english' => 'Al-\'Ankabut', 'name_transliteration' => 'Al-ʿAnkabūt', 'revelation_type' => 'Meccan', 'total_verses' => 69],
            ['surah_number' => 30, 'name_arabic' => 'الروم', 'name_english' => 'Ar-Rum', 'name_transliteration' => 'Ar-Rūm', 'revelation_type' => 'Meccan', 'total_verses' => 60],
            ['surah_number' => 31, 'name_arabic' => 'لقمان', 'name_english' => 'Luqman', 'name_transliteration' => 'Luqmān', 'revelation_type' => 'Meccan', 'total_verses' => 34],
            ['surah_number' => 32, 'name_arabic' => 'السجدة', 'name_english' => 'As-Sajdah', 'name_transliteration' => 'As-Sajdah', 'revelation_type' => 'Meccan', 'total_verses' => 30],
            ['surah_number' => 33, 'name_arabic' => 'الأحزاب', 'name_english' => 'Al-Ahzab', 'name_transliteration' => 'Al-Aḥzāb', 'revelation_type' => 'Medinan', 'total_verses' => 73],
            ['surah_number' => 34, 'name_arabic' => 'سبأ', 'name_english' => 'Saba', 'name_transliteration' => 'Sabaʾ', 'revelation_type' => 'Meccan', 'total_verses' => 54],
            ['surah_number' => 35, 'name_arabic' => 'فاطر', 'name_english' => 'Fatir', 'name_transliteration' => 'Fāṭir', 'revelation_type' => 'Meccan', 'total_verses' => 45],
            ['surah_number' => 36, 'name_arabic' => 'يس', 'name_english' => 'Ya-Sin', 'name_transliteration' => 'Yāsīn', 'revelation_type' => 'Meccan', 'total_verses' => 83],
            ['surah_number' => 37, 'name_arabic' => 'الصافات', 'name_english' => 'As-Saffat', 'name_transliteration' => 'Aṣ-Ṣāffāt', 'revelation_type' => 'Meccan', 'total_verses' => 182],
            ['surah_number' => 38, 'name_arabic' => 'ص', 'name_english' => 'Sad', 'name_transliteration' => 'Ṣād', 'revelation_type' => 'Meccan', 'total_verses' => 88],
            ['surah_number' => 39, 'name_arabic' => 'الزمر', 'name_english' => 'Az-Zumar', 'name_transliteration' => 'Az-Zumar', 'revelation_type' => 'Meccan', 'total_verses' => 75],
            ['surah_number' => 40, 'name_arabic' => 'غافر', 'name_english' => 'Ghafir', 'name_transliteration' => 'Ghāfir', 'revelation_type' => 'Meccan', 'total_verses' => 85],
            ['surah_number' => 41, 'name_arabic' => 'فصلت', 'name_english' => 'Fussilat', 'name_transliteration' => 'Fuṣṣilat', 'revelation_type' => 'Meccan', 'total_verses' => 54],
            ['surah_number' => 42, 'name_arabic' => 'الشورى', 'name_english' => 'Ash-Shuraa', 'name_transliteration' => 'Ash-Shūrā', 'revelation_type' => 'Meccan', 'total_verses' => 53],
            ['surah_number' => 43, 'name_arabic' => 'الزخرف', 'name_english' => 'Az-Zukhruf', 'name_transliteration' => 'Az-Zukhruf', 'revelation_type' => 'Meccan', 'total_verses' => 89],
            ['surah_number' => 44, 'name_arabic' => 'الدخان', 'name_english' => 'Ad-Dukhan', 'name_transliteration' => 'Ad-Dukhān', 'revelation_type' => 'Meccan', 'total_verses' => 59],
            ['surah_number' => 45, 'name_arabic' => 'الجاثية', 'name_english' => 'Al-Jathiyah', 'name_transliteration' => 'Al-Jāthiyah', 'revelation_type' => 'Meccan', 'total_verses' => 37],
            ['surah_number' => 46, 'name_arabic' => 'الأحقاف', 'name_english' => 'Al-Ahqaf', 'name_transliteration' => 'Al-Aḥqāf', 'revelation_type' => 'Meccan', 'total_verses' => 35],
            ['surah_number' => 47, 'name_arabic' => 'محمد', 'name_english' => 'Muhammad', 'name_transliteration' => 'Muḥammad', 'revelation_type' => 'Medinan', 'total_verses' => 38],
            ['surah_number' => 48, 'name_arabic' => 'الفتح', 'name_english' => 'Al-Fath', 'name_transliteration' => 'Al-Fatḥ', 'revelation_type' => 'Medinan', 'total_verses' => 29],
            ['surah_number' => 49, 'name_arabic' => 'الحجرات', 'name_english' => 'Al-Hujurat', 'name_transliteration' => 'Al-Ḥujurāt', 'revelation_type' => 'Medinan', 'total_verses' => 18],
            ['surah_number' => 50, 'name_arabic' => 'ق', 'name_english' => 'Qaf', 'name_transliteration' => 'Qāf', 'revelation_type' => 'Meccan', 'total_verses' => 45],
            ['surah_number' => 51, 'name_arabic' => 'الذاريات', 'name_english' => 'Adh-Dhariyat', 'name_transliteration' => 'Adh-Dhāriyāt', 'revelation_type' => 'Meccan', 'total_verses' => 60],
            ['surah_number' => 52, 'name_arabic' => 'الطور', 'name_english' => 'At-Tur', 'name_transliteration' => 'At-Ṭūr', 'revelation_type' => 'Meccan', 'total_verses' => 49],
            ['surah_number' => 53, 'name_arabic' => 'النجم', 'name_english' => 'An-Najm', 'name_transliteration' => 'An-Najm', 'revelation_type' => 'Meccan', 'total_verses' => 62],
            ['surah_number' => 54, 'name_arabic' => 'القمر', 'name_english' => 'Al-Qamar', 'name_transliteration' => 'Al-Qamar', 'revelation_type' => 'Meccan', 'total_verses' => 55],
            ['surah_number' => 55, 'name_arabic' => 'الرحمن', 'name_english' => 'Ar-Rahman', 'name_transliteration' => 'Ar-Raḥmān', 'revelation_type' => 'Medinan', 'total_verses' => 78],
            ['surah_number' => 56, 'name_arabic' => 'الواقعة', 'name_english' => 'Al-Waqi\'ah', 'name_transliteration' => 'Al-Wāqiʿah', 'revelation_type' => 'Meccan', 'total_verses' => 96],
            ['surah_number' => 57, 'name_arabic' => 'الحديد', 'name_english' => 'Al-Hadid', 'name_transliteration' => 'Al-Ḥadīd', 'revelation_type' => 'Medinan', 'total_verses' => 29],
            ['surah_number' => 58, 'name_arabic' => 'المجادلة', 'name_english' => 'Al-Mujadila', 'name_transliteration' => 'Al-Mujādila', 'revelation_type' => 'Medinan', 'total_verses' => 22],
            ['surah_number' => 59, 'name_arabic' => 'الحشر', 'name_english' => 'Al-Hashr', 'name_transliteration' => 'Al-Ḥashr', 'revelation_type' => 'Medinan', 'total_verses' => 24],
            ['surah_number' => 60, 'name_arabic' => 'الممتحنة', 'name_english' => 'Al-Mumtahanah', 'name_transliteration' => 'Al-Mumtaḥanah', 'revelation_type' => 'Medinan', 'total_verses' => 13],
            ['surah_number' => 61, 'name_arabic' => 'الصف', 'name_english' => 'As-Saf', 'name_transliteration' => 'Aṣ-Ṣaff', 'revelation_type' => 'Medinan', 'total_verses' => 14],
            ['surah_number' => 62, 'name_arabic' => 'الجمعة', 'name_english' => 'Al-Jumu\'ah', 'name_transliteration' => 'Al-Jumuʿah', 'revelation_type' => 'Medinan', 'total_verses' => 11],
            ['surah_number' => 63, 'name_arabic' => 'المنافقون', 'name_english' => 'Al-Munafiqun', 'name_transliteration' => 'Al-Munāfiqūn', 'revelation_type' => 'Medinan', 'total_verses' => 11],
            ['surah_number' => 64, 'name_arabic' => 'التغابن', 'name_english' => 'At-Taghabun', 'name_transliteration' => 'At-Taghābun', 'revelation_type' => 'Medinan', 'total_verses' => 18],
            ['surah_number' => 65, 'name_arabic' => 'الطلاق', 'name_english' => 'At-Talaq', 'name_transliteration' => 'At-Ṭalāq', 'revelation_type' => 'Medinan', 'total_verses' => 12],
            ['surah_number' => 66, 'name_arabic' => 'التحريم', 'name_english' => 'At-Tahrim', 'name_transliteration' => 'At-Taḥrīm', 'revelation_type' => 'Medinan', 'total_verses' => 12],
            ['surah_number' => 67, 'name_arabic' => 'الملك', 'name_english' => 'Al-Mulk', 'name_transliteration' => 'Al-Mulk', 'revelation_type' => 'Meccan', 'total_verses' => 30],
            ['surah_number' => 68, 'name_arabic' => 'القلم', 'name_english' => 'Al-Qalam', 'name_transliteration' => 'Al-Qalam', 'revelation_type' => 'Meccan', 'total_verses' => 52],
            ['surah_number' => 69, 'name_arabic' => 'الحاقة', 'name_english' => 'Al-Haqqah', 'name_transliteration' => 'Al-Ḥāqqah', 'revelation_type' => 'Meccan', 'total_verses' => 52],
            ['surah_number' => 70, 'name_arabic' => 'المعارج', 'name_english' => 'Al-Ma\'arij', 'name_transliteration' => 'Al-Maʿārij', 'revelation_type' => 'Meccan', 'total_verses' => 44],
            ['surah_number' => 71, 'name_arabic' => 'نوح', 'name_english' => 'Nuh', 'name_transliteration' => 'Nūḥ', 'revelation_type' => 'Meccan', 'total_verses' => 28],
            ['surah_number' => 72, 'name_arabic' => 'الجن', 'name_english' => 'Al-Jinn', 'name_transliteration' => 'Al-Jinn', 'revelation_type' => 'Meccan', 'total_verses' => 28],
            ['surah_number' => 73, 'name_arabic' => 'المزمل', 'name_english' => 'Al-Muzzammil', 'name_transliteration' => 'Al-Muzzammil', 'revelation_type' => 'Meccan', 'total_verses' => 20],
            ['surah_number' => 74, 'name_arabic' => 'المدثر', 'name_english' => 'Al-Muddaththir', 'name_transliteration' => 'Al-Muddaththir', 'revelation_type' => 'Meccan', 'total_verses' => 56],
            ['surah_number' => 75, 'name_arabic' => 'القيامة', 'name_english' => 'Al-Qiyamah', 'name_transliteration' => 'Al-Qiyāmah', 'revelation_type' => 'Meccan', 'total_verses' => 40],
            ['surah_number' => 76, 'name_arabic' => 'الإنسان', 'name_english' => 'Al-Insan', 'name_transliteration' => 'Al-Insān', 'revelation_type' => 'Medinan', 'total_verses' => 31],
            ['surah_number' => 77, 'name_arabic' => 'المرسلات', 'name_english' => 'Al-Mursalat', 'name_transliteration' => 'Al-Mursalāt', 'revelation_type' => 'Meccan', 'total_verses' => 50],
            ['surah_number' => 78, 'name_arabic' => 'النبأ', 'name_english' => 'An-Naba', 'name_transliteration' => 'An-Nabaʾ', 'revelation_type' => 'Meccan', 'total_verses' => 40],
            ['surah_number' => 79, 'name_arabic' => 'النازعات', 'name_english' => 'An-Naziat', 'name_transliteration' => 'An-Nāziʿāt', 'revelation_type' => 'Meccan', 'total_verses' => 46],
            ['surah_number' => 80, 'name_arabic' => 'عبس', 'name_english' => 'Abasa', 'name_transliteration' => 'ʿAbasa', 'revelation_type' => 'Meccan', 'total_verses' => 42],
            ['surah_number' => 81, 'name_arabic' => 'التكوير', 'name_english' => 'At-Takwir', 'name_transliteration' => 'At-Takwīr', 'revelation_type' => 'Meccan', 'total_verses' => 29],
            ['surah_number' => 82, 'name_arabic' => 'الإنفطار', 'name_english' => 'Al-Infitar', 'name_transliteration' => 'Al-Infiṭār', 'revelation_type' => 'Meccan', 'total_verses' => 19],
            ['surah_number' => 83, 'name_arabic' => 'المطففين', 'name_english' => 'Al-Mutaffifin', 'name_transliteration' => 'Al-Muṭaffifīn', 'revelation_type' => 'Meccan', 'total_verses' => 36],
            ['surah_number' => 84, 'name_arabic' => 'الإنشقاق', 'name_english' => 'Al-Inshiqaq', 'name_transliteration' => 'Al-Inshiqāq', 'revelation_type' => 'Meccan', 'total_verses' => 25],
            ['surah_number' => 85, 'name_arabic' => 'البروج', 'name_english' => 'Al-Buruj', 'name_transliteration' => 'Al-Burūj', 'revelation_type' => 'Meccan', 'total_verses' => 22],
            ['surah_number' => 86, 'name_arabic' => 'الطارق', 'name_english' => 'At-Tariq', 'name_transliteration' => 'At-Ṭāriq', 'revelation_type' => 'Meccan', 'total_verses' => 17],
            ['surah_number' => 87, 'name_arabic' => 'الأعلى', 'name_english' => 'Al-A\'la', 'name_transliteration' => 'Al-Aʿlā', 'revelation_type' => 'Meccan', 'total_verses' => 19],
            ['surah_number' => 88, 'name_arabic' => 'الغاشية', 'name_english' => 'Al-Ghashiyah', 'name_transliteration' => 'Al-Ghāshiyah', 'revelation_type' => 'Meccan', 'total_verses' => 26],
            ['surah_number' => 89, 'name_arabic' => 'الفجر', 'name_english' => 'Al-Fajr', 'name_transliteration' => 'Al-Fajr', 'revelation_type' => 'Meccan', 'total_verses' => 30],
            ['surah_number' => 90, 'name_arabic' => 'البلد', 'name_english' => 'Al-Balad', 'name_transliteration' => 'Al-Balad', 'revelation_type' => 'Meccan', 'total_verses' => 20],
            ['surah_number' => 91, 'name_arabic' => 'الشمس', 'name_english' => 'Ash-Shams', 'name_transliteration' => 'Ash-Shams', 'revelation_type' => 'Meccan', 'total_verses' => 15],
            ['surah_number' => 92, 'name_arabic' => 'الليل', 'name_english' => 'Al-Layl', 'name_transliteration' => 'Al-Layl', 'revelation_type' => 'Meccan', 'total_verses' => 21],
            ['surah_number' => 93, 'name_arabic' => 'الضحى', 'name_english' => 'Ad-Duhaa', 'name_transliteration' => 'Aḍ-Ḍuḥā', 'revelation_type' => 'Meccan', 'total_verses' => 11],
            ['surah_number' => 94, 'name_arabic' => 'الشرح', 'name_english' => 'Ash-Sharh', 'name_transliteration' => 'Ash-Sharḥ', 'revelation_type' => 'Meccan', 'total_verses' => 8],
            ['surah_number' => 95, 'name_arabic' => 'التين', 'name_english' => 'At-Tin', 'name_transliteration' => 'At-Tīn', 'revelation_type' => 'Meccan', 'total_verses' => 8],
            ['surah_number' => 96, 'name_arabic' => 'العلق', 'name_english' => 'Al-Alaq', 'name_transliteration' => 'Al-ʿAlaq', 'revelation_type' => 'Meccan', 'total_verses' => 19],
            ['surah_number' => 97, 'name_arabic' => 'القدر', 'name_english' => 'Al-Qadr', 'name_transliteration' => 'Al-Qadr', 'revelation_type' => 'Meccan', 'total_verses' => 5],
            ['surah_number' => 98, 'name_arabic' => 'البينة', 'name_english' => 'Al-Bayyinah', 'name_transliteration' => 'Al-Bayyinah', 'revelation_type' => 'Medinan', 'total_verses' => 8],
            ['surah_number' => 99, 'name_arabic' => 'الزلزلة', 'name_english' => 'Az-Zalzalah', 'name_transliteration' => 'Az-Zalzalah', 'revelation_type' => 'Medinan', 'total_verses' => 8],
            ['surah_number' => 100, 'name_arabic' => 'العاديات', 'name_english' => 'Al-Adiyat', 'name_transliteration' => 'Al-ʿĀdiyāt', 'revelation_type' => 'Meccan', 'total_verses' => 11],
            ['surah_number' => 101, 'name_arabic' => 'القارعة', 'name_english' => 'Al-Qari\'ah', 'name_transliteration' => 'Al-Qāriʿah', 'revelation_type' => 'Meccan', 'total_verses' => 11],
            ['surah_number' => 102, 'name_arabic' => 'التكاثر', 'name_english' => 'At-Takathur', 'name_transliteration' => 'At-Takāthur', 'revelation_type' => 'Meccan', 'total_verses' => 8],
            ['surah_number' => 103, 'name_arabic' => 'العصر', 'name_english' => 'Al-Asr', 'name_transliteration' => 'Al-ʿAṣr', 'revelation_type' => 'Meccan', 'total_verses' => 3],
            ['surah_number' => 104, 'name_arabic' => 'الهمزة', 'name_english' => 'Al-Humazah', 'name_transliteration' => 'Al-Humazah', 'revelation_type' => 'Meccan', 'total_verses' => 9],
            ['surah_number' => 105, 'name_arabic' => 'الفيل', 'name_english' => 'Al-Fil', 'name_transliteration' => 'Al-Fīl', 'revelation_type' => 'Meccan', 'total_verses' => 5],
            ['surah_number' => 106, 'name_arabic' => 'قريش', 'name_english' => 'Quraysh', 'name_transliteration' => 'Quraysh', 'revelation_type' => 'Meccan', 'total_verses' => 4],
            ['surah_number' => 107, 'name_arabic' => 'الماعون', 'name_english' => 'Al-Ma\'un', 'name_transliteration' => 'Al-Māʿūn', 'revelation_type' => 'Meccan', 'total_verses' => 7],
            ['surah_number' => 108, 'name_arabic' => 'الكوثر', 'name_english' => 'Al-Kawthar', 'name_transliteration' => 'Al-Kawthar', 'revelation_type' => 'Meccan', 'total_verses' => 3],
            ['surah_number' => 109, 'name_arabic' => 'الكافرون', 'name_english' => 'Al-Kafirun', 'name_transliteration' => 'Al-Kāfirūn', 'revelation_type' => 'Meccan', 'total_verses' => 6],
            ['surah_number' => 110, 'name_arabic' => 'النصر', 'name_english' => 'An-Nasr', 'name_transliteration' => 'An-Naṣr', 'revelation_type' => 'Medinan', 'total_verses' => 3],
            ['surah_number' => 111, 'name_arabic' => 'المسد', 'name_english' => 'Al-Masad', 'name_transliteration' => 'Al-Masad', 'revelation_type' => 'Meccan', 'total_verses' => 5],
            ['surah_number' => 112, 'name_arabic' => 'الإخلاص', 'name_english' => 'Al-Ikhlas', 'name_transliteration' => 'Al-Ikhlāṣ', 'revelation_type' => 'Meccan', 'total_verses' => 4],
            ['surah_number' => 113, 'name_arabic' => 'الفلق', 'name_english' => 'Al-Falaq', 'name_transliteration' => 'Al-Falaq', 'revelation_type' => 'Meccan', 'total_verses' => 5],
            ['surah_number' => 114, 'name_arabic' => 'الناس', 'name_english' => 'An-Nas', 'name_transliteration' => 'An-Nās', 'revelation_type' => 'Meccan', 'total_verses' => 6],
        ];

        foreach ($surahs as $surah) {
            Surah::updateOrCreate(
                ['surah_number' => $surah['surah_number']], 
                $surah
            );
        }
    }
}